# Generated by Django 4.2.2 on 2023-06-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cursos", models.CharField(max_length=255)),
                ("nome_coordenador", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("periodos", models.IntegerField()),
                ("imagem", models.ImageField(upload_to="imagens")),
            ],
        ),
    ]
